{% set name = "cget" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 835009ba6d623a36eee8056975d7cdbeebb0e0091a058b572ed433fb12ae18e8

build:
  noarch: python
  number: 0
  entry_points:
    - cget = cget.cli:cli
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click >=6.6
    - six >=1.10
    - cmake
    - subprocess32

test:
  imports:
    - cget
  commands:
    - cget --help

about:
  home: https://github.com/pfultz2/cget
  license: BSL-1.0
  license_file: LICENSE
  summary: Cmake package retrieval. This can be used to download and install cmake packages.

  description: |
    Cmake package retrieval. This can be used to download and install cmake packages.
    Advantages are non-intrusivenes, use out of the box, and decentralization.
    No need to change cmake scripts, cget works almost any cmake package and packages
    can be installed from anywhere.
  doc_url: https://cget.readthedocs.io/en/latest/
  dev_url: https://github.com/pfultz2/cget

extra:
  recipe-maintainers:
    - matuskosut
